[package]
name = "npgs_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
strum = {version = "0.26.2", features = ["std", "derive"]}
