#pragma once

#include "Engine/Base/NpgsObject/Astro/CelestialObject.h"
#include "Engine/Base/NpgsObject/Astro/Planet.h"
#include "Engine/Base/NpgsObject/Astro/Star.h"
#include "Engine/Base/NpgsObject/Civilization.h"
#include "Engine/Base/NpgsObject/NpgsObject.h"
#include "Engine/Base/StellarSystem.h"

#include "Engine/Core/AssetLoader/AssetManager.h"
#include "Engine/Core/AssetLoader/Csv.hpp"
#include "Engine/Core/Modules/CivilizationGenerator.h"
#include "Engine/Core/Modules/OrbitalGenerator.h"
#include "Engine/Core/Modules/StellarClass.h"
#include "Engine/Core/Modules/StellarGenerator.h"
#include "Engine/Core/Universe/Universe.h"
#include "Engine/Core/Utilities/Logger.h"
#include "Engine/Core/Utilities/Octree.hpp"
#include "Engine/Core/Utilities/Random.hpp"
#include "Engine/Core/Utilities/ThreadPool.h"
#include "Engine/Core/Assert.h"
#include "Engine/Core/Base.h"
#include "Engine/Core/Constants.h"
